const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Particles,
		C3.Behaviors.DragnDrop
	];
};
self.C3_JsPropNameTable = [
	{bg_kapak: 0},
	{kapak_baslik: 0},
	{btn_basla: 0},
	{btn_bilgi: 0},
	{bilgi: 0},
	{btn_kaynakca: 0},
	{btn_anasayfa: 0},
	{bg_oyun: 0},
	{a: 0},
	{b: 0},
	{c: 0},
	{d: 0},
	{e: 0},
	{btn_zor: 0},
	{btn_orta: 0},
	{btn_kolay: 0},
	{bg_video: 0},
	{btn_ileri: 0},
	{btn_geri: 0},
	{bnt_cikis: 0},
	{a2: 0},
	{arkaplan: 0},
	{final_yazi: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{bg_secim: 0},
	{btn_nasil_oynanir: 0},
	{Tween: 0},
	{btn_basla2: 0},
	{bg_info: 0},
	{btn_cikis: 0},
	{Particles: 0},
	{Particles2: 0},
	{DragDrop: 0},
	{motifler: 0}
];

self.InstanceType = {
	bg_kapak: class extends self.ISpriteInstance {},
	kapak_baslik: class extends self.ISpriteInstance {},
	btn_basla: class extends self.ISpriteInstance {},
	btn_bilgi: class extends self.ISpriteInstance {},
	bilgi: class extends self.ISpriteInstance {},
	btn_kaynakca: class extends self.ISpriteInstance {},
	btn_anasayfa: class extends self.ISpriteInstance {},
	bg_oyun: class extends self.ISpriteInstance {},
	a: class extends self.ISpriteInstance {},
	b: class extends self.ISpriteInstance {},
	c: class extends self.ISpriteInstance {},
	d: class extends self.ISpriteInstance {},
	e: class extends self.ISpriteInstance {},
	btn_zor: class extends self.ISpriteInstance {},
	btn_orta: class extends self.ISpriteInstance {},
	btn_kolay: class extends self.ISpriteInstance {},
	bg_video: class extends self.ISpriteInstance {},
	btn_ileri: class extends self.ISpriteInstance {},
	btn_geri: class extends self.ISpriteInstance {},
	bnt_cikis: class extends self.ISpriteInstance {},
	a2: class extends self.ISpriteInstance {},
	arkaplan: class extends self.ISpriteInstance {},
	final_yazi: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	bg_secim: class extends self.ISpriteInstance {},
	btn_nasil_oynanir: class extends self.ISpriteInstance {},
	btn_basla2: class extends self.ISpriteInstance {},
	bg_info: class extends self.ISpriteInstance {},
	btn_cikis: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Particles2: class extends self.IParticlesInstance {},
	motifler: class extends self.ISpriteInstance {}
}